from datetime import datetime
from typing import Optional, Dict, Any


class AnalysisReport:
    """
    Domain entity representing the analysis report generated by LLM and visualization.
    Contains KPI summary, table summaries, and ratio analysis.
    """

    def __init__(
        self,
        statement_id: int,
        kpi_summary: Optional[str] = None,
        statement_table_summary: Optional[Dict[str, Any]] = None,
        ratio_analysis: Optional[str] = None,
        report_s3_key: Optional[str] = None
    ):
        self.id: Optional[int] = None
        self.statement_id = statement_id
        self.kpi_summary = kpi_summary
        self.statement_table_summary = statement_table_summary
        self.ratio_analysis = ratio_analysis
        self.report_s3_key = report_s3_key
        self.created_at: datetime = datetime.utcnow()

        self._validate()

    def _validate(self):
        """Validate business rules"""
        if self.statement_id is None or self.statement_id <= 0:
            raise ValueError("Statement ID must be positive")

    def set_kpi_summary(self, summary: str):
        """Set KPI summary from LLM analysis"""
        if not summary or len(summary.strip()) == 0:
            raise ValueError("KPI summary cannot be empty")

        if len(summary) > 5000:
            raise ValueError("KPI summary too long (max 5000 characters)")

        self.kpi_summary = summary

    def set_statement_table_summary(self, table_summary: Dict[str, Any]):
        """Set financial statement table summary"""
        if not table_summary:
            raise ValueError("Table summary cannot be empty")

        # Validate structure
        required_keys = ["balance_sheet_summary", "income_statement_summary"]
        for key in required_keys:
            if key not in table_summary:
                raise ValueError(f"Missing required table summary key: {key}")

        self.statement_table_summary = table_summary

    def set_ratio_analysis(self, analysis: str):
        """Set ratio analysis interpretation from LLM"""
        if not analysis or len(analysis.strip()) == 0:
            raise ValueError("Ratio analysis cannot be empty")

        if len(analysis) > 5000:
            raise ValueError("Ratio analysis too long (max 5000 characters)")

        self.ratio_analysis = analysis

    def set_report_s3_key(self, s3_key: str):
        """Set S3 key for generated PDF report"""
        if not s3_key or len(s3_key.strip()) == 0:
            raise ValueError("Report S3 key cannot be empty")

        self.report_s3_key = s3_key

    def is_complete(self) -> bool:
        """Check if report has all required sections"""
        return (
            self.kpi_summary is not None and
            self.statement_table_summary is not None and
            self.ratio_analysis is not None and
            self.report_s3_key is not None
        )

    def has_llm_analysis(self) -> bool:
        """Check if LLM analysis sections are complete"""
        return (
            self.kpi_summary is not None and
            self.statement_table_summary is not None and
            self.ratio_analysis is not None
        )

    def get_balance_sheet_summary(self) -> Optional[Dict[str, Any]]:
        """Extract balance sheet summary"""
        if self.statement_table_summary is None:
            return None
        return self.statement_table_summary.get("balance_sheet_summary")

    def get_income_statement_summary(self) -> Optional[Dict[str, Any]]:
        """Extract income statement summary"""
        if self.statement_table_summary is None:
            return None
        return self.statement_table_summary.get("income_statement_summary")

    def __repr__(self):
        return (
            f"AnalysisReport(id={self.id}, statement_id={self.statement_id}, "
            f"complete={self.is_complete()}, created_at={self.created_at})"
        )
